import type { Service } from '@/entities/cart';
import Airplane from '@/shared/assets/Image/airplane.jpg';
import Bag from '@/shared/assets/Image/bag.jpg';
import Document from '@/shared/assets/Image/document.jpg';
import Food from '@/shared/assets/Image/food.jpg';
import Menu from '@/shared/assets/Image/menu.jpg';
import Place from '@/shared/assets/Image/place.jpg';

export const mockServices: Service[] = [
    {
        id: '1',
        title: 'Дополнительный багаж',
        description: 'Добавьте к провозу 10 кг багажа сверх нормы',
        price: 50,
        currency: '$',
        imageUrl: Bag,
    },
    {
        id: '2',
        title: 'Страхование полета',
        description: 'Полная страховка на время перелета и стыковок',
        price: 25,
        currency: '$',
        imageUrl: Document,
    },
    {
        id: '3',
        title: 'Премиум питание',
        description: 'Специальное меню от шеф-повара с выбором блюд',
        price: 35,
        currency: '$',
        imageUrl: Food,
    },
    {
        id: '4',
        title: 'Приоритетная посадка',
        description: 'Посадка в первой группе без очереди',
        price: 20,
        currency: '$',
        imageUrl: Place,
    },
    {
        id: '5',
        title: 'Дополнительное место',
        description: 'Бронирование соседнего кресла для комфорта',
        price: 150,
        currency: '$',
        imageUrl: Place,
    },
    {
        id: '6',
        title: 'Премиум-зал ожидания',
        description: 'Доступ в бизнес-лаунж с питанием и напитками',
        price: 75,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '7',
        title: 'Wi-Fi на борту',
        description: 'Высокоскоростной интернет на протяжении всего полета',
        price: 15,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '8',
        title: 'Детское меню',
        description: 'Специальное питание для детей с игрушкой в подарок',
        price: 18,
        currency: '$',
        imageUrl: Menu,
    },
    {
        id: '9',
        title: 'Вегетарианское питание',
        description: 'Полноценное меню без мясных продуктов',
        price: 22,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '10',
        title: 'Трансфер в аэропорт',
        description: 'Комфортабельный трансфер от двери до терминала',
        price: 60,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '11',
        title: 'Повышение класса',
        description: 'Апгрейд до бизнес-класса при наличии мест',
        price: 300,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '12',
        title: 'Спортивный инвентарь',
        description: 'Перевоз лыж, сноуборда или велосипеда',
        price: 45,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '13',
        title: 'Медицинская страховка',
        description: 'Страховка на случай болезни в поездке',
        price: 30,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '14',
        title: 'Горячее питание',
        description: 'Теплый обед или ужин на борту',
        price: 28,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '15',
        title: 'Дополнительная подушка',
        description: 'Ортопедическая подушка для комфортного сна',
        price: 12,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '16',
        title: 'Плед повышенной комфортности',
        description: 'Теплый плед из натуральных материалов',
        price: 10,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '17',
        title: 'Наушники премиум-класса',
        description: 'Шумоподавляющие наушники для просмотра фильмов',
        price: 25,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '18',
        title: 'Мобильное приложение',
        description: 'Премиум-версия приложения без рекламы',
        price: 5,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '19',
        title: 'Экскурсия в аэропорту',
        description: 'Обзорная экскурсия по аэропорту во время стыковки',
        price: 40,
        currency: '$',
        imageUrl: Airplane,
    },
    {
        id: '20',
        title: 'Фотосессия на борту',
        description: 'Профессиональная фотосессия с экипажем',
        price: 65,
        currency: '$',
        imageUrl: Airplane,
    },
];
